# Generated by Django 5.2 on 2025-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('send_notification', 'Kirim Notifikasi'), ('generate_report', 'Buat Laporan'), ('send_email', 'Kirim Email'), ('process_ticket', 'Proses Tiket')], max_length=50, verbose_name='Jenis Tugas')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Sedang Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20, verbose_name='Status')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Hasil')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir diperbarui')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Dijadwalkan pada')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dieksekusi pada')),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Tugas',
                'ordering': ['-created_at'],
            },
        ),
    ]
